name: openworkflow_dart
description: A workflow JSON Spec Parser for dart with service.
version: 0.1.0
repository: https://github.com/LiteVar/openworkflow_dart

environment:
  sdk: ^3.4.3

dependencies:
  opentool_dart:
    path: /Users/jan/Project/openspec_dart/opentool_dart
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
